### ISSUE TITLE
dart 2.9 打开空安全后全错了，有计划兼容嘛？

### ISSUE THREAD

**Issue by TshineZheng** [debuggerx01/JSONFormat4Flutter#30]
刚升了 Flutter 1.20，并尝试迁移代码到 non-nullable，突然发现用这个工具生成的 json 代码全部都报错了。

**Comment by debuggerx01** [comment]
我更新了以后没碰到你说的错误 能详细说下什么情况吗

**Comment by TshineZheng** [comment]
@debuggerx01 空安全打开了吗？
升到最新的话 dart 应该是 2.9。
`analysis_options.yaml` 文件中加入
```yaml
analyzer:
  enable-experiment:
    - non-nullable
```
调整`pubspec.yaml`中的sdk版本为
```yaml
environment:
  sdk: ">=2.9.0 <3.0.0"
```
